import React, {useState} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Store Manager</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Store Manager</h1>
        <form className={styles.userInput}>
          <label>
            Number of items:<input type='text'/>
          </label>
        </form>
      </main>
    </div>
  )
}
